### ISSUE TITLE
Can I export to two different sheets in an Excel file?

### ISSUE THREAD

**Issue by mallim** [Haulmont/yarg#6]
Hi 

This library looks interesting.

Is there an example to show how to export to two different sheets?

Thanks

**Comment by tinhol** [comment]
Hello.

There is no need for special settings to use several sheets.
You just put named range to the certain sheet, and then the library put band data there.

Please let me know if you still need an example, and I will add it to the examples.

**Comment by mallim** [comment]
Thanks for the headsup, I will take another look at the example
